# Site settings
title: Li Yi's Person World
email: liyisepku@gmail.com
description: > this is my personal site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liyionline.me" # the base hostname & protocol for your site
twitter_username: samuelliyi
github_username:  samuel-liyi

# Build settings
markdown: kramdown
