# Site settings
title: Li Yi's Personal World
email: liyi@liyionline.me
description: > # this means to ignore newlines until "baseurl:"
  This is my personal website, where I put all things related to my work,
  study and personal life
baseurl: "/cn/" # the subpath of your site, e.g. /blog/
#url: "http://liyionline.me/cn" # the base hostname & protocol for your site
twitter_username: samuelliyi
github_username:  samuel-liyi
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

# Build settings
markdown: kramdown
destination:
# Outputting
permalink: /cn/:year/:month/:day/:title.html
